# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c9a78f0d417f4600fbe4cde1c1c7b933445625a1ffa0b37aabd2f23bc0af84b2b3ced7bef5d0c182ace00e2541189cdd0b82477c53334774e1e13de6ed3ee1a

test:
  secret_key_base: c1a56f76daaabe0828b09a50bf0509b06b217f056ba8708950ca0a1d82e6469cd754ee2297acead89e1fcc35f44d3271aec3e7f418a5dd7ec9feef8c1477ee14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
